version: '3'

services:
  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_ENV=apm-test
      - DD_SERVICE=flask_app_demo
      - DD_VERSION=1.0
    depends_on:
      - datadog-agent
